/**
 * TitleBar Component Styles
 */

import type { JSX } from "solid-js";

export const titleBarStyles = {
  container: (): JSX.CSSProperties => ({
    display: "flex",
    "align-items": "center",
    "justify-content": "space-between",
    width: "100%",
    height: "var(--title-bar-height)",
    "background-color": "hsl(var(--title-bar-background))",
    "user-select": "none",
    "-webkit-app-region": "drag" as const,
    "box-sizing": "border-box",
    padding: "0",
    margin: "0",
    position: "relative" as const,
    "z-index": "1000",
    border: "none",
  }),
  leftSection: {
    display: "flex",
    "align-items": "center",
    height: "100%",
    "flex-shrink": "0",
  },
  burgerButton: (): JSX.CSSProperties => ({
    "-webkit-app-region": "no-drag" as const,
    width: "var(--title-bar-button-size)",
    height: "var(--title-bar-button-size)",
    display: "flex",
    "align-items": "center",
    "justify-content": "center",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    padding: "0",
    margin: "0",
    color: "hsl(var(--foreground))",
    transition: "background-color 150ms cubic-bezier(0.4, 0, 0.2, 1)",
  }),
  titleArea: (): JSX.CSSProperties => ({
    display: "flex",
    "align-items": "center",
    flex: "1",
    height: "100%",
    padding: "0 12px",
    overflow: "hidden",
    "text-overflow": "ellipsis",
    "white-space": "nowrap",
    color: "hsl(var(--foreground))",
    "font-size": "var(--font-size-sm)",
    "font-weight": "400",
    "letter-spacing": "0.01em",
  }),
  rightSection: {
    display: "flex",
    "align-items": "center",
    height: "100%",
    "flex-shrink": "0",
    "-webkit-app-region": "no-drag" as const,
  },
  controlsGroup: {
    display: "flex",
    "align-items": "center",
    height: "100%",
    gap: "0",
  },
  separator: (): JSX.CSSProperties => ({
    width: "1px",
    height: "20px",
    "background-color": "hsl(var(--border))",
    margin: "0 4px",
  }),
  controlButton: {
    width: "var(--title-bar-button-size)",
    height: "var(--title-bar-button-size)",
    display: "flex",
    "align-items": "center",
    "justify-content": "center",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    padding: "0",
    margin: "0",
    color: "hsl(var(--foreground))",
    transition: "background-color 150ms cubic-bezier(0.4, 0, 0.2, 1)",
  },
  controlButtonHover: {
    "background-color": "hsla(var(--primary-hover) / 0.1)",
  },
  closeButtonHover: {
    "background-color": "var(--button-close-hover)",
  },
};
